apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
  namespace: geoserver
  labels:
    app: geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
        - name: geoserver
          image: docker.osgeo.org/geoserver:2.26.2
          ports:
            - name: geoserver
              containerPort: 8080
          env:
            - name: GEOSERVER_ADMIN_PASSWORD
              value: "geoserver"
          volumeMounts:
            - mountPath: "/opt/geoserver"
              name: geoserver-data
      volumes:
        - name: geoserver-data
          persistentVolumeClaim:
            claimName: geoserver-pvc
